services:
  app:
    container_name: sva_app
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - .:/app
    env_file:
      - .env  
    environment:
      REDIS_HOST: ${REDIS_HOST:-sva_redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      TELEMETRY_API_URL: ${TELEMETRY_API_URL:-https://dev-vistaar.da.gov.in/observability-service/action/data/v3/telemetry}
    restart: unless-stopped
    networks:
      - svanetwork
      
networks:
  svanetwork:
    external: true
